name: Auto approve

on:
  pull_request:
    branches:
      - master
      - 'skipped*'
jobs:
  building:
    name: lgtm
    runs-on: ubuntu-latest
    steps:
      - name: fetching..
        uses: michaelgichia/javacsript-action@master
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "skipped*"
          PULL_REQUEST_BRANCH: "master"