# name: "units-test"
# on:
#   pull_request:
#   push:
#     branches:
#       - master
#       - 'releases/*'

# jobs:
#   # unit tests
#   units:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: michaelgichia/javacsript-actiont@v4
#     - run: npm ci

on: pull_request

jobs:
  one:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"